version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: mysql_test_db
    ports:
      - '3306:3306'
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
